import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/appSideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          {/* Entire app fixed to viewport */}
          <div className="flex h-screen w-full overflow-hidden">
            {/* Sidebar (fixed height) */}
            <div className="flex-shrink-0">
              <AppSidebar />
            </div>

            {/* Main content scrolls */}
            <main className="flex-1 min-w-0 overflow-y-auto p-6">
              {children}
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
